### ISSUE TITLE
Bug Ckan "Last Modified"

### ISSUE THREAD

**Issue by Mvpl** [NextGeoss/bug-tracking#12] opened 2018-08-14 13:12 UTC
- [X] Bug
- [ ] Feature request

Use [X] to mark bug or feature

### Site URL:
http://localhost:5000/organization/dlr

### What steps can be taken to reproduce the issue? (Attach screenshots if available)
Go into the url and try to order by "Last Modified"

### Please describe the actual behaviour (Attach screenshots if available)
When you go to a list of datasets you have options to sort it. The option "Last Modified" is not working. This is a bug that need to be resolved in order to figure out what was the first dataset harvested.

### Please describe the expected behaviour
When in a list of datasets if we have an option to sort it by "Last Modified"  we expect it to sort the dataset by the dates, from the last modified to the first modified

**Comment by kmbn** [comment] 2018-08-22 10:40
The "Last Modified" option is working as designed. In this context, "last" means "most recently", so the first search result is the dataset whatever dataset was most recently modified (or created) and the last search result is the dataset with the oldest modification (or creation) date.

The default sorting for search results is relevance (most relevant to least relevant) followed by modification date (most recent to least recent). When you visit a page like http://localhost:5000/organization/dlr, the search results you see are effectively already sorted by "Last Modified". All of them belong to the `dlr` organization, so each result is equally relevant and the only attribute that matters for sorting is the modification date. If you redo the search with the "Last Modified" sorting option, it will seem like the option had no effect because the two searches are essentially the same: find all the `dlr` datasets and then order them by modification date.

The labels of the search result sorting options and the default sort order are both determined by CKAN itself and not by the data hub.

**Comment by michellecbox** [comment] 2018-08-27 08:18
@Mvpl I am closing this bug "as designed". Let us know if you have any comments/questions.

**Closed by michellecbox** 2018-08-27 08:18 UTC
