### ISSUE TITLE
Server error when accessing a dataset

### ISSUE THREAD

**Issue by joaandrade** [NextGeoss/bug-tracking#10] opened 2018-07-13 10:01 UTC
- [X] Bug
- [ ] Feature request

Use [X] to mark bug or feature

### Site URL:
https://catalogue.nextgeoss.eu/dataset/s1a_iw_grdh_1sdv_20180122t035536_20180122t035601_020262_02296d_5edb

### What steps can be taken to reproduce the issue? (Attach screenshots if available)
1) Access https://catalogue.nextgeoss.eu
2) Insert NextGEOSS credentials
3) Access the "Datasets" tab
4) Click in a dataset

### Please describe the actual behaviour (Attach screenshots if available)
Server Error is displayed

### Please describe the expected behaviour
The dataset page should be displayed

**Comment by joaandrade** [comment] 2018-07-13 10:05
![server_error_when_accessing_a_dataset](https://user-images.githubusercontent.com/8322111/42686024-909c8988-868c-11e8-8b68-921be7999af2.png)

**Comment by michellecbox** [comment] 2018-07-19 08:49
Not repro, can you retry @joaandrade

**Comment by joaandrade** [comment] 2018-07-19 08:52
I'm getting the server error when I try to access for example:

https://catalogue.nextgeoss.eu/dataset/s1a_iw_grdh_1sdv_20180125t060207_20180125t060232_020307_022ad6_5728

**Comment by michellecbox** [comment] 2018-07-19 12:59
@joaandrade Is it possible that you are looking at a cached copy of the page?
I am still not able to reproduce it following both URLs you added.

![image](https://user-images.githubusercontent.com/13909143/42943827-3313d62c-8b64-11e8-9e40-66ccc6fdbf0b.png)
![image](https://user-images.githubusercontent.com/13909143/42943860-52138c34-8b64-11e8-9a41-3433a1ca0151.png)

**Comment by joaandrade** [comment] 2018-07-19 13:11
@michellecbox I've tested in a different browser and in a different computer. The Server Error remains.
Permissions??

**Comment by michellecbox** [comment] 2018-07-20 12:31
@joaandrade can you please try using username and password: **externaltester**
this user has a non-Viderum email address and should be able to log in to the data hub and see all the content

**Comment by joaandrade** [comment] 2018-07-20 12:35
@michellecbox I've tested with the External tester and it worked. However, with my user (already added as a discoverBetaUser) the issue remains.

**Comment by michellecbox** [comment] 2018-07-20 14:07
@joaandrade one possibility we can think of is that the encoding of the ã is causing the issue with your user.

Before doing anything, can you touch base with your colleagues and see if they're having the same issue?

if they don't then you could create a new user without ã on the UM and ask Héctor to give you discoverUserBeta rights.

**Comment by joaandrade** [comment] 2018-07-20 14:11
@michellecbox I will Héctor to give permissions to one of my colleagues and will come back after the test

**Comment by woksoll** [comment] 2018-07-31 13:46
I can login in properly but I ca see only 3 datasets. There should be 300,000 The server is still buggy.

**Comment by michellecbox** [comment] 2018-08-03 07:51
Closing this issue since the server error does not appear. The incorrect number of datasets being shown is a separate issue, currently being worked by @kmbn

**Closed by michellecbox** 2018-08-03 07:51 UTC

**Comment by joaandrade** [comment] 2018-08-20 09:49
Just to confirm that the error was only on my side. The name of the user should not contain special characters. My profile was updated from "João" to "Joao" and the Server Error just disappeared.
